### ISSUE TITLE
reload info

### ISSUE THREAD

**Issue by andresbelt** [sberoch/RickAndMorty-AndroidArchitectureSample#2]
Hello, I think it's excellent the way you do the cache and the call to the server but what would you do if you delete the whole database and you want to reload the data from the network, calling again the LiveData doesn't do it, could you explain me?  

thank you

**Comment by sberoch** [comment]
There should be a way to update the network content, totally agree! Maybe using a SwipeRefreshLayout that when triggered will call the vm and repo methods to update. Feel free to send a pull request!
